Vagrant.configure("2") do |config|

  config.vm.box = "eurolinux-vagrant/centos-stream-9"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "private_network", ip: "192.168.50.20"

  config.vm.network "public_network"

  config.vm.synced_folder "../html_data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|

  vb.memory = "4096"
  end
 
  config.vm.provision "shell", inline: <<-SHELL
  yum install httpd wget vim unzip zip -y
  systemctl start httpd 
  systemctl enable httpd
  cp -r /vagrant_data/* /var/www/html/
  SHELL
end

